# Generated by Django 5.2.5 on 2025-10-25 13:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tz_str', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('open_1', models.CharField(help_text='HH:MM', max_length=5)),
                ('close_1', models.CharField(help_text='HH:MM', max_length=5)),
                ('open_2', models.CharField(blank=True, default='', max_length=5)),
                ('close_2', models.CharField(blank=True, default='', max_length=5)),
                ('holidays_calendar_key', models.CharField(blank=True, default='', max_length=64)),
                ('pre_open_handling', models.CharField(choices=[('ignore', 'ignore'), ('clip', 'clip')], default='ignore', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TradingAsset',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('index', 'Index'), ('sector', 'Sector'), ('commodity', 'Commodity'), ('crypto', 'Crypto')], max_length=12)),
                ('symbol', models.CharField(blank=True, default='', max_length=80)),
                ('exchange', models.CharField(default='NSE', max_length=16)),
                ('tz', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('status', models.CharField(default='active', max_length=12)),
                ('session_rules', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.sessionrules')),
            ],
        ),
        migrations.CreateModel(
            name='AssetNatal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_utc', models.DateTimeField()),
                ('tz', models.CharField(default='UTC', max_length=64)),
                ('lat', models.FloatField(default=19.076)),
                ('lon', models.FloatField(default=72.8777)),
                ('location_name', models.CharField(default='Mumbai', max_length=80)),
                ('source_note', models.TextField(blank=True, default='')),
                ('accuracy', models.CharField(choices=[('exact', 'exact'), ('noon', 'noon'), ('day', 'day')], default='day', max_length=12)),
                ('include_overlay', models.BooleanField(default=False)),
                ('overlay_weight_preset', models.CharField(choices=[('conservative', 'conservative'), ('standard', 'standard'), ('aggressive', 'aggressive')], default='conservative', max_length=16)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingasset')),
            ],
        ),
        migrations.CreateModel(
            name='TradingDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tz', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('session_start', models.CharField(max_length=5)),
                ('session_end', models.CharField(max_length=5)),
                ('bands', models.JSONField(default=list)),
                ('engine_version', models.CharField(default='1.0.0', max_length=16)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingasset')),
            ],
            options={
                'indexes': [models.Index(fields=['asset', 'date'], name='trading_tra_asset_i_74aa36_idx')],
                'unique_together': {('asset', 'date')},
            },
        ),
    ]
