entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml

# Only enable these two lines on EC2 (TLS). Keep them commented locally.
# certificatesResolvers:
#   letsencrypt:
#     acme:
#       email: you@example.com
#       storage: /letsencrypt/acme.json
#       httpChallenge:
#         entryPoint: web
