# Generated by Django 5.2.5 on 2025-10-24 01:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0002_alter_dailyreport_unique_together_chart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='horoscope',
            name='user',
        ),
        migrations.DeleteModel(
            name='Planet',
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['user', 'created_at'], name='astro_chart_user_id_d020fe_idx'),
        ),
        migrations.DeleteModel(
            name='DailyReport',
        ),
        migrations.DeleteModel(
            name='Horoscope',
        ),
    ]
